reduction: sum
criterions:
  -
    name: heatmap_loss
    target_key: TARGET_LANDMARKS_HEATMAP
    output_key: OUTPUT_LANDMARKS_HEATMAP
    weight: 1.
    loss:
      _target_: model_training.losses.IoULoss

  -
    name: vertices3d_loss
    target_key: TARGET_3D_MODEL_VERTICES
    output_key: OUTPUT_3D_VERTICES  # Now uses pre-computed 3D vertices from model
    weight: 50.
    loss:
      _target_: model_training.losses.Vertices3DLossDirect
      criterion: l2 # choose from {l1, l2, smooth_l1}
      weights_and_indices:
        flame_indices: ${train.flame_indices}
        weights: {'head': .5, 'face_w_ears': .75, 'face': 1.}


  - name: reprojection_loss
    target_key: TARGET_2D_FULL_LANDMARKS
    output_key: OUTPUT_2D_VERTICES  # Now uses pre-computed 2D vertices from model
    weight: 0.05
    loss:
      _target_: model_training.losses.ReprojectionLossDirect
      criterion: smooth_l1
      weights_and_indices:
        flame_indices: ${train.flame_indices}
        weights: {'face': .5, 'face_w_ears': .5}

  - name: landmarks_loss
    target_key:
      - TARGET_2D_LANDMARKS
      - TARGET_2D_LANDMARKS_PRESENCE
    output_key:
      - OUTPUT_2D_LANDMARKS
      - TARGET_2D_LANDMARKS_PRESENCE
    weight: 100.
    loss:
      _target_: model_training.losses.LandmarksLossWVisibility
      criterion: smooth_l1

  - name: region_iou
    target_key: TARGET_FACE_REGION
    output_key: OUTPUT_REGION
    weight: 1.0
    loss:
      _target_: model_training.losses.IoULoss

  - name: region_bce
    target_key: TARGET_FACE_REGION
    output_key: OUTPUT_REGION
    weight: 1.0
    loss:
      _target_: model_training.losses.BCELoss


  - name: depth_smoothl1_masked
    target_key:
      - TARGET_FACE_DEPTH         # target depth
      - TARGET_FACE_REGION        # mask
    output_key:
      - OUTPUT_DEPTH              # pred logits
    weight: 2
    loss:
      _target_: model_training.losses.SigmoidSmoothL1Masked
      beta: 1.0
